### ISSUE TITLE
Error Serializing Arrays with Null Values

### ISSUE THREAD

**Issue by GoogleCodeExporter** [confile/gwt-streamer#6]
```
What steps will reproduce the problem?
1. Create class A with an array of Strings
2. Create an object of A populating an array where at least one of the strings 
is null
3. Serialize the object on the client

What is the expected output? What do you see instead?
SEVERE: (TypeError) : Cannot read property 'length' of null
com.google.gwt.core.client.JavaScriptException: (TypeError) : Cannot read 
property 'length' of null
    at Unknown.wrap_4_g$(Exceptions.java:36)
    at Unknown.$length_13_g$(String.java:758)
    at Unknown.length__I__devirtual$_1_g$(String.java:757)
    at Unknown.getBytesUtf8_0_g$(String.java:457)
    at Unknown.$getBytes_1_g$(String.java:679)
    at Unknown.getBytes_Ljava_lang_String___B__devirtual$_0_g$(String.java:677)
    at Unknown.writeString_1_g$(Base64PackedStreamFactory.java:202)
    at Unknown.writeString_2_g$(WriteContext.java:250)
    at Unknown.writeObject_16_g$(SimpleArrayStreamers.java:255)
    at Unknown.writeObject_4_g$(WriteContext.java:129)
    at Unknown.writeObjectData_0_g$(StructStreamer.java:46)
    at Unknown.writeObject_2_g$(StructStreamer.java:21)
    at Unknown.writeObject_4_g$(WriteContext.java:129)
    at Unknown.writeObjectData_1_g$(CollectionStreamer.java:38)
    at Unknown.writeObject_5_g$(CollectionStreamer.java:16)
    at Unknown.writeObject_4_g$(WriteContext.java:129)
    at Unknown.writeObjectData_0_g$(StructStreamer.java:46)
    at Unknown.writeObject_2_g$(StructStreamer.java:21)
    at Unknown.writeObject_4_g$(WriteContext.java:129)
    at Unknown.writeObject_1_g$(Streamer.java:259)
    at Unknown.toString_38_g$(Streamer.java:215)
    at Unknown.onSuccess_4_g$(IDocsServiceCacheImpl.java:85)
    at Unknown.onSuccess_5_g$(IDocsServiceCacheImpl.java:83)
    at Unknown.onResponseReceived_0_g$(RequestCallbackAdapter.java:232)
    at Unknown.fireOnResponseReceived_0_g$(Request.java:250)
    at Unknown.onReadyStateChange_0_g$(RequestBuilder.java:412)
    at Unknown.anonymous(XMLHttpRequest.java:329)
    at Unknown.apply_0_g$(Impl.java:247)
    at Unknown.entry0_0_g$(Impl.java:299)
    at Unknown.anonymous(Impl.java:72)


What version of the product are you using? On what operating system?
2.0.0

Please provide any additional information below.


```

Original issue reported on code.google.com by `adzin...@gmail.com` on 17 Apr 2015 at 8:27

**Comment by GoogleCodeExporter** [comment]
```
BTW, thank you for the library, it is looking really good!
```

Original comment by `adzin...@gmail.com` on 17 Apr 2015 at 9:07
